[package]
name = "fin-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"
quick-xml = { version = "0.38.3", features = ["serialize"] }
clap = { version = "4.5.51", features = ["derive"] }
